name: "YAML Variable substitution"
description: "Replaces value form a yml file"
inputs:
  inputFile:
    description: "Name and path of the input file"
    required: true
  outputFile:
    description: "Name and path of the output INPUT_FILE"
    required: true
  params:
    description: "Separated list of key-value pairs to be replaced"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.params }}