name: "YAML Variable substitution"
description: "Replaces value form a yml file"
inputs:
  input_file:
    description: "Name and path of the input file"
    required: true
  output_file:
    description: "Name and path of the output INPUT_FILE"
    required: true
  params:
    description: "Separated list of key-value pairs to be replaced"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.params }}