name: Test action
on:
  [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Builds yml file
        uses: ./
        with:
          inputFile: 'test/test.yml'
          outputFile: 'output.yml'
          params: "--remove:languages.pascal --replace:languages.perl='Noob' --replace:employed=False --replace:foods=['Chips', 'Steak'] --append:hobbies='Reading' --append:hobbies='Football'  --add:languages.java='Major'"
      - name: Upload output file
        uses: actions/upload-artifact@v1
        with:
          name: test.yml
          path: output.yml